/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/renderer/src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/renderer/src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/renderer/src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/renderer/src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/renderer/src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/renderer/src/components/icons/IconTooling.vue')['default']
    ResponsiveImage: typeof import('./src/renderer/src/components/ResponsiveImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/renderer/src/components/TheWelcome.vue')['default']
    UpLoad: typeof import('./src/renderer/src/components/UpLoad.vue')['default']
    Versions: typeof import('./src/renderer/src/components/Versions.vue')['default']
    WelcomeItem: typeof import('./src/renderer/src/components/WelcomeItem.vue')['default']
  }
}
